export const apiKey=process.env.NEXT_PUBLIC_FIREBASE_API_KEY
export const authDomain=process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
export const projectId=process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID
export const storageBucket=process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
export const messagingSenderId=process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
export const appId=process.env.NEXT_PUBLIC_FIREBASE_APP_ID
export const measurementId=process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
export const emailJSServiceId=process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID || ''
export const emailJSTemplateId=process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID || ''
export const emailJSUserId=process.env.NEXT_PUBLIC_EMAILJS_USER_ID || ''
